In [ ]:
1. Load the dataset using pandas
2. Extract data fromYearsExperience column is a variable named X
3. Extract data from salary column is a variable named Y
4. Divide the dataset into two parts for training and testing in 66% and 33% proportion
5. Create and train LinearRegression Model on training set
6. Make predictions based on the testing set using the trained model
7. Check the performance by calculating the r2 score of the mode

In [ ]:
#1. Load the dataset using pandas
import pandas as pd
data=pd.read_csv("/content/data.csv")
data

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [ ]:
#2. Extract data fromYearsExperience column is a variable named X
x=data["YearsExperience"]
x

0      1.1
1      1.3
2      1.5
3      2.0
4      2.2
5      2.9
6      3.0
7      3.2
8      3.2
9      3.7
10     3.9
11     4.0
12     4.0
13     4.1
14     4.5
15     4.9
16     5.1
17     5.3
18     5.9
19     6.0
20     6.8
21     7.1
22     7.9
23     8.2
24     8.7
25     9.0
26     9.5
27     9.6
28    10.3
29    10.5
Name: YearsExperience, dtype: float64

In [ ]:
#3. Extract data from salary column is a variable named Y
y=data["Salary"]
y

0      39343.0
1      46205.0
2      37731.0
3      43525.0
4      39891.0
5      56642.0
6      60150.0
7      54445.0
8      64445.0
9      57189.0
10     63218.0
11     55794.0
12     56957.0
13     57081.0
14     61111.0
15     67938.0
16     66029.0
17     83088.0
18     81363.0
19     93940.0
20     91738.0
21     98273.0
22    101302.0
23    113812.0
24    109431.0
25    105582.0
26    116969.0
27    112635.0
28    122391.0
29    121872.0
Name: Salary, dtype: float64

In [ ]:
#4. Divide the dataset into two parts for training and testing in 66% and 33% proportion
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)
x_train

4      2.2
16     5.1
5      2.9
13     4.1
11     4.0
22     7.9
1      1.3
2      1.5
25     9.0
3      2.0
21     7.1
26     9.5
18     5.9
29    10.5
20     6.8
7      3.2
10     3.9
14     4.5
19     6.0
6      3.0
Name: YearsExperience, dtype: float64

In [ ]:
x_train_reshaped=x_train.values.reshape(-1,1)
y_train_reshaped=y_train.values.reshape(-1,1)
x_test_reshaped=x_test.values.reshape(-1,1)
y_test_reshaped=y_test.values.reshape(-1,1)
x_train_reshaped

array([[ 2.2],
       [ 5.1],
       [ 2.9],
       [ 4.1],
       [ 4. ],
       [ 7.9],
       [ 1.3],
       [ 1.5],
       [ 9. ],
       [ 2. ],
       [ 7.1],
       [ 9.5],
       [ 5.9],
       [10.5],
       [ 6.8],
       [ 3.2],
       [ 3.9],
       [ 4.5],
       [ 6. ],
       [ 3. ]])

In [ ]:
#5. Create and train LinearRegression Model on training set
from sklearn.linear_model import LinearRegression
lin_reg=LinearRegression().fit(x_train_reshaped,y_train_reshaped)
lin_reg

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
#6. Make predictions based on the testing set using the trained model

In [ ]:
y_pred=lin_reg.predict(x_test_reshaped)
y_pred

array([[115814.30756236],
       [ 71511.92534771],
       [102617.85328566],
       [ 75282.34085534],
       [ 55487.65944028],
       [ 60200.67882482],
       [122412.53470072],
       [107330.8726702 ],
       [ 63028.49045554],
       [ 35692.97802523]])

In [ ]:
y_train_reshaped

array([[ 39891.],
       [ 66029.],
       [ 56642.],
       [ 57081.],
       [ 55794.],
       [101302.],
       [ 46205.],
       [ 37731.],
       [105582.],
       [ 43525.],
       [ 98273.],
       [116969.],
       [ 81363.],
       [121872.],
       [ 91738.],
       [ 54445.],
       [ 63218.],
       [ 61111.],
       [ 93940.],
       [ 60150.]])

In [ ]:
y_train_pred=lin_reg.predict(x_train_reshaped)
y_train_pred

array([[ 46061.62067121],
       [ 73397.13310153],
       [ 52659.84780956],
       [ 63971.09433245],
       [ 63028.49045554],
       [ 99790.04165494],
       [ 37578.18577904],
       [ 39463.39353286],
       [110158.68430092],
       [ 44176.41291739],
       [ 92249.21063968],
       [114871.70368546],
       [ 80937.96411679],
       [124297.74245453],
       [ 89421.39900895],
       [ 55487.65944028],
       [ 62085.88657864],
       [ 67741.50984008],
       [ 81880.56799369],
       [ 53602.45168647]])

In [ ]:
x_test_reshaped

array([[ 9.6],
       [ 4.9],
       [ 8.2],
       [ 5.3],
       [ 3.2],
       [ 3.7],
       [10.3],
       [ 8.7],
       [ 4. ],
       [ 1.1]])

In [ ]:
print(lin_reg.coef_)

[[9426.03876907]]


In [ ]:
print(lin_reg.intercept_)

[25324.33537924]


In [ ]:
#7. Check the performance by calculating the r2 score of the model
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
print(r2_score(y_train_reshaped,y_train_pred))

0.9549236946181227


In [ ]:
print(mean_squared_error(y_train_reshaped,y_train_pred))

29793161.082422983


# **Decision Tree**

In [ ]:
1. Load the dataset using pandas
2. Extract data fromOutcome column is a variable named Y
3. Extract data from every column except Outcome column in a variable named X
4. Divide the dataset into two parts for training and testing in 70% and 30% proportion
5. Create and train Decision Tree Model on training set
6. Make predictions based on the testing set using the trained model
7. Check the performance by calculating the confusion matrix and accuracy score of the model 

In [ ]:
import pandas as pd

In [ ]:
#1. Load the dataset using pandas
data2=pd.read_csv("/content/diabetes.csv")
data2

Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]

In [ ]:
#2. Extract data from Outcome column is a variable named Y
y=data2["Outcome"]
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [ ]:
#3. Extract data from every column except Outcome column in a variable named X
x=data2.iloc[:,:-1]
x

Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0              6      148             72  ...  33.6                     0.627   50
1              1       85             66  ...  26.6                     0.351   31
2              8      183             64  ...  23.3                     0.672   32
3              1       89             66  ...  28.1                     0.167   21
4              0      137             40  ...  43.1                     2.288   33
..           ...      ...            ...  ...   ...                       ...  ...
763           10      101             76  ...  32.9                     0.171   63
764            2      122             70  ...  36.8                     0.340   27
765            5      121             72  ...  26.2                     0.245   30
766            1      126             60  ...  30.1                     0.349   47
767            1       93             70  ...  30.4                     0.315   23

[768 rows x 8 columns]

In [ ]:
#4. Divide the dataset into two parts for training and testing in 70% and 30% proportion
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [ ]:
#5. Create and train Decision Tree Model on training set
from sklearn.tree import DecisionTreeClassifier

In [ ]:
classifier=DecisionTreeClassifier()
classifier.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
#6. Make predictions based on the testing set using the trained model
y_pred=classifier.predict(x_test)
y_pred

array([0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [ ]:
#7. Check the performance by calculating the confusion matrix and accuracy score of the model 

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[106,  45],
       [ 25,  55]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.696969696969697